DATA TRANSFORMATION

In [2]:
import pandas as pd

data = pd.read_csv("data_sample.csv")
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [3]:
data.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [4]:
data.drop_duplicates(inplace = True)

In [5]:
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [8]:
data["Age"].fillna(data["Age"].mean(),inplace = True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_13356\450382181.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].mean(),inplace = True)

In [9]:
data

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.00        Delhi      F     eve@domain.com         NaN

In [12]:
data["Name"][5] = "Eve"

C:\Users\Admin\AppData\Local\Temp\ipykernel_13356\4269853338.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data["Name"][5] = "Eve"
C:\Users\Admin\AppData\Local\Temp\ipykernel_13356\4269853338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Name"][5] = "Eve"

In [13]:
data

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      Eve  28.00        Delhi      F     eve@domain.com         NaN

In [14]:
data

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      Eve  28.00        Delhi      F     eve@domain.com         NaN

In [19]:
data["Join Date"][5] = "12-12-2020"

C:\Users\Admin\AppData\Local\Temp\ipykernel_13356\1351396307.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data["Join Date"][5] = "12-12-2020"
C:\Users\Admin\AppData\Local\Temp\ipykernel_13356\1351396307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Join Date"][5] = "12-12-2020"

In [20]:
data

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020

In [21]:
data.sort_values("Age")

      Name    Age         City Gender              Email   Join Date
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020

In [25]:
data.sort_values(["Age","Join Date"],ascending=False)

      Name    Age         City Gender              Email   Join Date
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
4    David  22.00       Mumbai      M  david@example.com  12-11-2019

In [26]:
data.reset_index(drop = True)

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
3    David  22.00       Mumbai      M  david@example.com  12-11-2019
4      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020

In [27]:
data

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020

In [28]:
data.sort_index()

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020

In [29]:
#Ranking 
data["Rank"] = data["Age"].rank(ascending = False)

In [30]:
data

      Name    Age         City Gender              Email   Join Date  Rank
0    Alice  25.00     New York      F  alice@example.com  01-05-2021   4.0
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020   1.0
4    David  22.00       Mumbai      M  david@example.com  12-11-2019   5.0
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020   2.0

In [31]:
data["Rank"] = data["Age"].rank()

In [32]:
data

      Name    Age         City Gender              Email   Join Date  Rank
0    Alice  25.00     New York      F  alice@example.com  01-05-2021   2.0
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020   5.0
4    David  22.00       Mumbai      M  david@example.com  12-11-2019   1.0
5      Eve  28.00        Delhi      F     eve@domain.com  12-12-2020   4.0

In [34]:
#Renaming columns and index
#ITS SYNTAXS
#df.rename(columns = {"oldname":"newName"},inplace = True)
data.rename(columns = {"Gender":"Sex"},inplace = True)

In [35]:
data

      Name    Age         City Sex              Email   Join Date  Rank
0    Alice  25.00     New York   F  alice@example.com  01-05-2021   2.0
1  Charlie  26.25        Delhi   M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles   M    bob@example.com  15-06-2020   5.0
4    David  22.00       Mumbai   M  david@example.com  12-11-2019   1.0
5      Eve  28.00        Delhi   F     eve@domain.com  12-12-2020   4.0

In [36]:
df1 = data.copy()

In [37]:
df1

      Name    Age         City Sex              Email   Join Date  Rank
0    Alice  25.00     New York   F  alice@example.com  01-05-2021   2.0
1  Charlie  26.25        Delhi   M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles   M    bob@example.com  15-06-2020   5.0
4    David  22.00       Mumbai   M  david@example.com  12-11-2019   1.0
5      Eve  28.00        Delhi   F     eve@domain.com  12-12-2020   4.0

In [38]:
#Changing The names of all the columns in the given 
df1.columns = ["name","age","city","sex","email","join date","rank"]

In [39]:
df1

      name    age         city sex              email   join date  rank
0    Alice  25.00     New York   F  alice@example.com  01-05-2021   2.0
1  Charlie  26.25        Delhi   M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles   M    bob@example.com  15-06-2020   5.0
4    David  22.00       Mumbai   M  david@example.com  12-11-2019   1.0
5      Eve  28.00        Delhi   F     eve@domain.com  12-12-2020   4.0

In [40]:
data

      Name    Age         City Sex              Email   Join Date  Rank
0    Alice  25.00     New York   F  alice@example.com  01-05-2021   2.0
1  Charlie  26.25        Delhi   M    charlie@example  20-07-2021   3.0
2      Bob  30.00  Los Angeles   M    bob@example.com  15-06-2020   5.0
4    David  22.00       Mumbai   M  david@example.com  12-11-2019   1.0
5      Eve  28.00        Delhi   F     eve@domain.com  12-12-2020   4.0

In [42]:
#Want to move one element to the front
cols = ["rank"] + [col for col in df1.columns if col != "rank"]
df1 = df1[cols]

In [43]:
df1

   rank     name    age         city sex              email   join date
0   2.0    Alice  25.00     New York   F  alice@example.com  01-05-2021
1   3.0  Charlie  26.25        Delhi   M    charlie@example  20-07-2021
2   5.0      Bob  30.00  Los Angeles   M    bob@example.com  15-06-2020
4   1.0    David  22.00       Mumbai   M  david@example.com  12-11-2019
5   4.0      Eve  28.00        Delhi   F     eve@domain.com  12-12-2020