DATA COLLECTION AND FILTERING

In [2]:
import pandas as pd
data = pd.read_excel("data.xlsx")
data

,JE Code,Store,Country,Region,Date,Item,Salesperson,List Price,Actual Price,Discount %
0,I-1001,Moscow,Russia,EMEA,2018-10-06 00:00:00,Microwave,May Wilmot,80,79,0.0125
1,I-1002,Toronto,Canada,NaN,4/23/2015,Microwave,David Shiner,80,54,0.3250
2,I-1003,Sao Paolo,Brazil,LATAM,2017-04-03 00:00:00,Air conditioner,Gary Reynolds,700,686,0.0200
3,I-1004,Istanbul,Turkey,EMEA,8/14/2018,Ceiling fan,Mark Buntain,150,137,0.0867
4,I-1005,Sydney,Australia,APAC,2015-03-03 00:00:00,Toaster,Christine Davies,50,37,0.2600
...,...,...,...,...,...,...,...,...,...,...
2334,I-3335,Vienna,Austria,EMEA,12/19/2017,Microwave,Raymond Denning,80,78,0.0250
2335,I-3336,Shenzhen,China,APAC,2/17/2015,Microwave,Phillip Humphreys,80,78,0.0250
2336,I-3337,Istanbul,Turkey,EMEA,5/27/2015,Washing Machine,David Philp,800,480,0.4000
2337,I-3338,Athens,Greece,EMEA,2016-07-10 00:00:00,Coffee grinder,Richard Perrott,70,64,0.0857
2338,I-3339,Shanghai,China,APAC,2017-02-09 00:00:00,Microwave,Glenys Raymond,80,77,0.0375

In [4]:
#Select Particular data from the given excel file
data["List Price"]

0        80
1        80
2       700
3       150
4        50
       ...
2334     80
2335     80
2336    800
2337     70
2338     80
Name: List Price, Length: 2339, dtype: int64

In [5]:
#selecting multiple data or fields from the given excel file
data[["List Price","Actual Price"]]

      List Price  Actual Price
0             80            79
1             80            54
2            700           686
3            150           137
4             50            37
...          ...           ...
2334          80            78
2335          80            78
2336         800           480
2337          70            64
2338          80            77

[2339 rows x 2 columns]

In [13]:
#Selecting rows by index (method1)
#It will give the complete row by label
data.loc[4]

JE Code                      I-1005
Store                        Sydney
Country                   Australia
Region                         APAC
Date            2015-03-03 00:00:00
Item                        Toaster
Salesperson        Christine Davies
List Price                       50
Actual Price                     37
Discount %                     0.26
Name: 4, dtype: object

In [16]:
#Selecting rows by index (method2)
#It will give the complete row by position
data.iloc[4]

JE Code                      I-1005
Store                        Sydney
Country                   Australia
Region                         APAC
Date            2015-03-03 00:00:00
Item                        Toaster
Salesperson        Christine Davies
List Price                       50
Actual Price                     37
Discount %                     0.26
Name: 4, dtype: object

In [18]:
#Selecting particular rows and columns 
data.loc[4,'Store']

'Sydney'

In [19]:
data.loc[3,'Store']

'Istanbul'

In [25]:
#By .iloc method
data.iloc[4,8]

np.int64(37)

In [34]:
data.loc[[2,7,8,9]]

,JE Code,Store,Country,Region,Date,Item,Salesperson,List Price,Actual Price,Discount %
2,I-1003,Sao Paolo,Brazil,LATAM,2017-04-03 00:00:00,Air conditioner,Gary Reynolds,700,686,0.0200
7,I-1008,Tijuana,Mexico,LATAM,2016-06-07 00:00:00,Iron,Gillian Allnutt,30,28,0.0667
8,I-1009,London,UK,EMEA,2015-12-11 00:00:00,Washing Machine,Francis Godden,800,760,0.0500
9,I-1010,Lima,Peru,LATAM,2014-09-07 00:00:00,Iron,Christopher Cresswell,30,28,0.0667

In [35]:
data.iloc[0:2,0:2]

  JE Code    Store
0  I-1001   Moscow
1  I-1002  Toronto

In [39]:
data.at[2,"Store"]

'Sao Paolo'

In [40]:
data.iat[0,0]

'I-1001'

In [49]:
#Collecting or selecting data accoring to conditions
data[data["List Price"]>500]

,JE Code,Store,Country,Region,Date,Item,Salesperson,List Price,Actual Price,Discount %
2,I-1003,Sao Paolo,Brazil,LATAM,2017-04-03 00:00:00,Air conditioner,Gary Reynolds,700,686,0.02
8,I-1009,London,UK,EMEA,2015-12-11 00:00:00,Washing Machine,Francis Godden,800,760,0.05
10,I-1011,Riyadh,Saudi Arabia,EMEA,2017-10-07 00:00:00,Refrigerator,Danny Brooks,1000,500,0.50
11,I-1012,Bangkok,Thailand,APAC,8/21/2014,Air conditioner,John Jenkins,700,679,0.03
14,I-1015,Sydney,Australia,APAC,2018-11-12 00:00:00,Washing Machine,James Ricketts,800,672,0.16
...,...,...,...,...,...,...,...,...,...,...
2317,I-3318,Chicago,USA,NaN,10/26/2017,Air conditioner,Derek Anderson,700,700,0.00
2329,I-3330,Rome,Italy,EMEA,2015-06-03 00:00:00,Refrigerator,Golam Reid,1000,650,0.35
2332,I-3333,Amsterdam,Netherlands,EMEA,2017-08-09 00:00:00,Air conditioner,Ian Christian,700,644,0.08
2333,I-3334,Istanbul,Turkey,EMEA,2015-10-06 00:00:00,Air conditioner,Cordia Alston,700,686,0.02
2336,I-3337,Istanbul,Turkey,EMEA,5/27/2015,Washing Machine,David Philp,800,480,0.40

In [51]:
data[(data["List Price"]>500) & (data["Actual Price"]>800)]

,JE Code,Store,Country,Region,Date,Item,Salesperson,List Price,Actual Price,Discount %
19,I-1020,Osaka,Japan,APAC,7/23/2016,Refrigerator,Kenneth Walter,1000,950,0.05
32,I-1033,Moscow,Russia,EMEA,10/19/2014,Refrigerator,Darren Brooks,1000,910,0.09
61,I-1062,Warsaw,Poland,EMEA,5/24/2014,Refrigerator,Hin Bragg,1000,810,0.19
64,I-1065,Shenzhen,China,APAC,3/16/2014,Refrigerator,Ronald Butler,1000,990,0.01
90,I-1091,Moscow,Russia,EMEA,11/20/2014,Refrigerator,Dermot Bailey,1000,880,0.12
...,...,...,...,...,...,...,...,...,...,...
2228,I-3229,Mexico City,Mexico,LATAM,2018-09-11 00:00:00,Refrigerator,James Anthony,1000,960,0.04
2229,I-3230,New York,USA,NaN,9/29/2016,Refrigerator,Sarah Houghton,1000,990,0.01
2264,I-3265,Cairo,Egypt,EMEA,11/30/2017,Refrigerator,David Amos,1000,860,0.14
2284,I-3285,Tel Aviv,Israel,EMEA,2014-02-08 00:00:00,Refrigerator,Richard McGrath,1000,840,0.16
2310,I-3311,Warsaw,Poland,EMEA,2017-09-07 00:00:00,Refrigerator,David Grey,1000,810,0.19

In [58]:
#Using the Query search method
data.query("`List Price` >= 500 and `Actual Price` == 990")

,JE Code,Store,Country,Region,Date,Item,Salesperson,List Price,Actual Price,Discount %
64,I-1065,Shenzhen,China,APAC,3/16/2014,Refrigerator,Ronald Butler,1000,990,0.01
1650,I-2651,San Fransisco,USA,NaN,4/28/2016,Refrigerator,James Bard,1000,990,0.01
2229,I-3230,New York,USA,NaN,9/29/2016,Refrigerator,Sarah Houghton,1000,990,0.01