DATA CLEANING AND PROCESSING

In [1]:
import pandas as pd

#firstly check weather the data is containing some null values are not
data = pd.read_csv("data_sample.csv")
data.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [2]:
#Counting the Missing Value per column
data.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [3]:
#to drop the nul value rows
df = data.copy()
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [5]:
data

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
#want to fill the null data with some values
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [7]:
#Replacing the null value to its columns average
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [8]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [22]:
#replacing the null value through help of forward and backward fill
df.ffill()

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021     Minor

In [10]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [11]:
#detecting and removing the duplicates values from the data
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [12]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [13]:
#to remove the duplicated value from the data
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [14]:
#Checking for duplicate values from multiple columns
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

STRING METHODS

In [15]:
#Converting particular columns to .lower()
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [16]:
#Checking for some conditions
df["City"].str.contains("delhi",case = False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [17]:
#Splitting
df["Email"].str.split("@")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [28]:
#Apply functions
df.fillna(18)
#df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
#df["Age Group"] = df["Age"].apply(lambda x:"Adult" if x >= 25 else "Minor")
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor

In [23]:
data
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     Minor
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Adult
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     Minor