Melt & Pivot

In [1]:
data = {
    "Name" : ["Alice","Bob","Charlie"],
    "Math" : [85,78,92],
    "science" : [90,45,75],
    "English" : [45,68,45]
}

In [2]:
import pandas as pd

data = pd.DataFrame(data)
data

      Name  Math  science  English
0    Alice    85       90       45
1      Bob    78       45       68
2  Charlie    92       75       45

In [8]:
#Using the Melt()
df1 = data.copy()
df1.melt(id_vars=['Name'],value_vars=["Math","science","English"],var_name="Subject",value_name="score")

      Name  Subject  score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  science     90
4      Bob  science     45
5  Charlie  science     75
6    Alice  English     45
7      Bob  English     68
8  Charlie  English     45

In [12]:
#Using the pivot method
df1.pivot(index="Name",columns="Subject",values="score")

KeyError: 'Subject'